import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { formatSkillsForPrompt, loadSkillsFromDir, type Skill } from "../packages/coding-agent/src/core/skills.ts";
import { parseFrontmatter } from "../packages/coding-agent/src/utils/frontmatter.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const skillsDirectory = join(repositoryRoot, "forge", "skills");
const reportPath = join(repositoryRoot, "FORGE_SKILLS.md");
const checkOnly = process.argv.slice(2).includes("--check");
const unknownOptions = process.argv.slice(2).filter((argument) => argument !== "--check");

if (unknownOptions.length > 0) {
	console.error(`Unknown option: ${unknownOptions[0]}`);
	process.exit(2);
}

function estimateTokens(text: string): number {
	return Math.ceil(text.length / 4);
}

function repositoryPath(path: string): string {
	return relative(repositoryRoot, path).split(sep).join("/");
}

function escapeMarkdown(value: string): string {
	return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function fallbackSummary(description: string): string {
	const firstSentence = description.match(/^.*?[.!?](?:\s|$)/)?.[0]?.trim() ?? description.trim();
	return firstSentence.length <= 96 ? firstSentence : `${firstSentence.slice(0, 93).trimEnd()}...`;
}

function loadSummary(skill: Skill): string {
	const metadataPath = join(skill.baseDir, "agents", "openai.yaml");
	if (!existsSync(metadataPath)) return fallbackSummary(skill.description);
	const metadata = parse(readFileSync(metadataPath, "utf8")) as unknown;
	if (!metadata || typeof metadata !== "object" || !("interface" in metadata)) {
		return fallbackSummary(skill.description);
	}
	const interfaceValue = metadata.interface;
	if (!interfaceValue || typeof interfaceValue !== "object" || !("short_description" in interfaceValue)) {
		return fallbackSummary(skill.description);
	}
	return typeof interfaceValue.short_description === "string"
		? interfaceValue.short_description
		: fallbackSummary(skill.description);
}

function withStablePath(skill: Skill): Skill {
	return { ...skill, filePath: repositoryPath(skill.filePath) };
}

function marginalLaunchCharacters(skill: Skill): number {
	if (skill.disableModelInvocation) return 0;
	const synthetic: Skill = {
		...skill,
		name: "report-measurement-sentinel",
		description: "Synthetic entry used only to isolate skill prompt overhead.",
		filePath: "forge/skills/report-measurement-sentinel/SKILL.md",
	};
	return formatSkillsForPrompt([synthetic, skill]).length - formatSkillsForPrompt([synthetic]).length;
}

const loaded = loadSkillsFromDir({ dir: skillsDirectory, source: "forge-profile" });
if (loaded.diagnostics.length > 0) {
	for (const diagnostic of loaded.diagnostics) {
		console.error(`${diagnostic.path}: ${diagnostic.message}`);
	}
	process.exit(1);
}

const skills = loaded.skills.map(withStablePath).sort((left, right) => left.name.localeCompare(right.name));
if (skills.length === 0) {
	console.error(`No skills found under ${skillsDirectory}`);
	process.exit(1);
}

const prompt = formatSkillsForPrompt(skills);
const launchPromptCharacters = prompt.length;
const launchPromptTokens = estimateTokens(prompt);
const entries = skills.map((skill) => {
	const absolutePath = resolve(repositoryRoot, skill.filePath);
	const raw = readFileSync(absolutePath, "utf8");
	const { body } = parseFrontmatter(raw);
	const launchCharacters = marginalLaunchCharacters(skill);
	return {
		name: skill.name,
		summary: loadSummary({ ...skill, baseDir: dirname(absolutePath) }),
		location: skill.filePath,
		modelVisible: !skill.disableModelInvocation,
		launchCharacters,
		launchTokens: Math.ceil(launchCharacters / 4),
		bodyTokens: estimateTokens(body),
		fileTokens: estimateTokens(raw),
	};
});
const visibleEntries = entries.filter((entry) => entry.modelVisible);
const sharedCharacters = launchPromptCharacters - visibleEntries.reduce((sum, entry) => sum + entry.launchCharacters, 0);
const sharedTokens = Math.ceil(sharedCharacters / 4);
const allFilesTokens = entries.reduce((sum, entry) => sum + entry.fileTokens, 0);

const lines = [
	"# Forge Skills Context Report",
	"",
	"> Generated by `npm run forge:skills-report`. Do not edit token counts manually.",
	"",
	"## Launch Context Summary",
	"",
	`- Available skills: ${entries.length}`,
	`- Model-visible skills at launch: ${visibleEntries.length}`,
	`- Estimated skill-related launch tokens: ${launchPromptTokens}`,
	`- Estimated shared skills-wrapper tokens: ${sharedTokens}`,
	`- Estimated tokens if every complete \`SKILL.md\` were later read: ${allFilesTokens}`,
	"",
	"The launch total covers only Pi's generated skills section. It excludes `AGENTS.md`, tool definitions, the rest of the system prompt, conversation history, and any skill body loaded later.",
	"",
	"## Skills",
	"",
	"| Skill | Summary | Launch metadata tokens | On-demand body tokens | Complete file tokens | Launch visibility |",
	"|---|---|---:|---:|---:|---|",
];

for (const entry of entries) {
	lines.push(
		`| [\`${escapeMarkdown(entry.name)}\`](${entry.location}) | ${escapeMarkdown(entry.summary)} | ${entry.launchTokens} | ${entry.bodyTokens} | ${entry.fileTokens} | ${entry.modelVisible ? "Model-visible" : "Manual invocation only"} |`,
	);
}

lines.push(
	"",
	"## Counting Method",
	"",
	"- Launch metadata is the exact XML entry produced by Pi's `formatSkillsForPrompt`, including the skill name, description, and normalized repository-relative location.",
	"- The total launch estimate is calculated from the complete generated skills section, including shared instructions and XML wrapper. Per-skill rounded estimates therefore may not sum exactly to the total.",
	"- Token estimates use Pi's conservative `ceil(characters / 4)` heuristic. Provider tokenizers produce different exact counts.",
	"- Repository-relative locations keep this report stable. Installed absolute paths can change the real launch count slightly.",
	"- On-demand body tokens exclude YAML frontmatter. Complete file tokens include it and approximate reading the entire file through the read tool.",
	"",
	"Regenerate after adding a skill or changing a skill name, description, location, body, or launch visibility:",
	"",
	"```bash",
	"npm run forge:skills-report",
	"```",
	"",
);

const report = `${lines.join("\n")}\n`;
if (checkOnly) {
	if (!existsSync(reportPath) || readFileSync(reportPath, "utf8") !== report) {
		console.error("FORGE_SKILLS.md is stale. Run: npm run forge:skills-report");
		process.exit(1);
	}
	console.log("FORGE_SKILLS.md is up to date.");
} else {
	writeFileSync(reportPath, report, "utf8");
	console.log(`Updated ${repositoryPath(reportPath)}`);
}
